/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Cat cat = new Cat("Barsik", 5, "Persik");
        System.out.println(cat.toString());
        cat.sounds();

        Parrot parrot = new Parrot("Kesha", 2, "Multicolor");
        System.out.printf("Age: %d, Color: %s", parrot.getAge(), parrot.getColor());
        parrot.sounds();

        Fish fish = new Fish("Karas", 20, "Carpovie");
        System.out.printf("Age: %s, Kind: %s", fish.getAge(), fish.getKind());
        fish.sounds();
    }
}
